/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv --include-runtime false cloudflare-env.d.ts` (hash: ddc028592dd2ed4ae3e60b1d4508fed8)
declare namespace Cloudflare {
	interface StagingEnv {
		UPLOADS_BUCKET: R2Bucket;
		HYPERDRIVE: Hyperdrive;
		ASSETS: Fetcher;
		NEXT_PUBLIC_CUBEJS_API_URL: string;
		NEXT_PUBLIC_CUBEJS_API_TOKEN: string;
		CLOUDFLARE_TUNNEL_TOKEN: string;
		MYSQL_ROOT_PASSWORD: string;
		MYSQL_APP_USER: string;
		MYSQL_APP_PASSWORD: string;
		MYSQL_DEV_ROOT_PASSWORD: string;
		ALLOWED_ORIGIN: string;
		AUTH_SECRET: string;
		AUTH_URL: string;
		NEXT_PUBLIC_SITE_URL: string;
		CRON_SECRET: string;
		CSRF_SECRET: string;
		DATABASE_URL: string;
		EASYSLIP_API_KEY: string;
		ENCRYPTION_KEY: string;
		NEXT_PUBLIC_TURNSTILE_SITE_KEY: string;
		TURNSTILE_SECRET_KEY: string;
		UPSTASH_REDIS_REST_TOKEN: string;
		UPSTASH_REDIS_REST_URL: string;
		RESEND_API_KEY: string;
		WORKER_SELF_REFERENCE: Fetcher /* my-game-store-staging */;
	}
	interface Env {
		UPLOADS_BUCKET: R2Bucket;
		HYPERDRIVE: Hyperdrive;
		ASSETS: Fetcher;
		NEXT_PUBLIC_CUBEJS_API_URL: string;
		NEXT_PUBLIC_CUBEJS_API_TOKEN: string;
		CLOUDFLARE_TUNNEL_TOKEN: string;
		MYSQL_ROOT_PASSWORD: string;
		MYSQL_APP_USER: string;
		MYSQL_APP_PASSWORD: string;
		MYSQL_DEV_ROOT_PASSWORD: string;
		ALLOWED_ORIGIN: string;
		AUTH_SECRET: string;
		AUTH_URL: string;
		NEXT_PUBLIC_SITE_URL: string;
		CRON_SECRET: string;
		CSRF_SECRET: string;
		DATABASE_URL: string;
		EASYSLIP_API_KEY: string;
		ENCRYPTION_KEY: string;
		NEXT_PUBLIC_TURNSTILE_SITE_KEY: string;
		TURNSTILE_SECRET_KEY: string;
		UPSTASH_REDIS_REST_TOKEN: string;
		UPSTASH_REDIS_REST_URL: string;
		RESEND_API_KEY: string;
		WORKER_SELF_REFERENCE: Fetcher /* my-game-store-staging */ | Fetcher /* my-game-store */;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXT_PUBLIC_CUBEJS_API_URL" | "NEXT_PUBLIC_CUBEJS_API_TOKEN" | "CLOUDFLARE_TUNNEL_TOKEN" | "MYSQL_ROOT_PASSWORD" | "MYSQL_APP_USER" | "MYSQL_APP_PASSWORD" | "MYSQL_DEV_ROOT_PASSWORD" | "ALLOWED_ORIGIN" | "AUTH_SECRET" | "AUTH_URL" | "NEXT_PUBLIC_SITE_URL" | "CRON_SECRET" | "CSRF_SECRET" | "DATABASE_URL" | "EASYSLIP_API_KEY" | "ENCRYPTION_KEY" | "NEXT_PUBLIC_TURNSTILE_SITE_KEY" | "TURNSTILE_SECRET_KEY" | "UPSTASH_REDIS_REST_TOKEN" | "UPSTASH_REDIS_REST_URL" | "RESEND_API_KEY">> {}
}
