export const API_ROUTES = {
    CSRF: "/api/csrf",
    SESSION: "/api/session",
    PROFILE: "/api/profile",
    PURCHASE: "/api/purchase",
    CART_REFRESH: "/api/cart/refresh",
    CART_CHECKOUT: "/api/cart/checkout",
    UPLOAD: "/api/upload",
    FEATURED_PRODUCTS: "/api/featured-products",
    PRODUCTS_LIST: "/api/products/list",
    SALE_PRODUCTS: "/api/sale-products",
    USER_BALANCE: "/api/user/balance",
    PROMO_CODE_VALIDATE: "/api/promo-codes/validate",
    GACHA_RECENT: "/api/gacha/recent",
    GACHA_ROLL: "/api/gacha/roll",
    GACHA_GRID_REWARDS: "/api/gacha/grid/rewards",
    QUEST_CLAIM: "/api/quests/claim",
    GACHA_GRID_ROLL: "/api/gacha/grid/roll",
    ADMIN_GACHA_REWARDS: "/api/admin/gacha-rewards",
    ADMIN_GACHA_REWARDS_UPLOAD_IMAGE: "/api/admin/gacha-rewards/upload-image",
    adminGachaReward: (id: string) => `/api/admin/gacha-rewards/${id}`,
} as const;
