import crypto from "crypto";
import { db, apiKeys, users } from "@/lib/db";
import { eq, and } from "drizzle-orm";
import { hasPermission, Permission } from "@/lib/permissions";

export function generateApiKey(): { rawKey: string; hashedKey: string; prefix: string } {
    const rawKey = crypto.randomBytes(32).toString("hex");
    const prefix = rawKey.substring(0, 8);
    const hashedKey = crypto.createHash("sha256").update(rawKey).digest("hex");
    return { rawKey, hashedKey, prefix };
}

export function hashApiKey(rawKey: string): string {
    return crypto.createHash("sha256").update(rawKey).digest("hex");
}

export async function validateApiKey(rawKey: string): Promise<{
    valid: boolean;
    userId?: string;
    permissions?: string[];
    error?: string;
}> {
    if (!rawKey || rawKey.length !== 64) return { valid: false, error: "Invalid API key format" };

    const hashedKey = hashApiKey(rawKey);
    const prefix = rawKey.substring(0, 8);

    const apiKey = await db.query.apiKeys.findFirst({
        where: and(
            eq(apiKeys.key, hashedKey),
            eq(apiKeys.keyPrefix, prefix),
            eq(apiKeys.isActive, true)
        ),
        with: {
            user: { columns: { id: true, role: true, permissions: true } },
        },
    });

    if (!apiKey) return { valid: false, error: "API key not found or inactive" };

    if (apiKey.expiresAt && new Date(apiKey.expiresAt) < new Date()) {
        return { valid: false, error: "API key expired" };
    }

    await db.update(apiKeys)
        .set({ lastUsedAt: new Date().toISOString().slice(0, 19).replace("T", " ") })
        .where(eq(apiKeys.id, apiKey.id));

    const permissions = apiKey.permissions ? JSON.parse(apiKey.permissions) : [];
    return { valid: true, userId: apiKey.userId, permissions };
}

export async function createApiKey(
    userId: string,
    name: string,
    permissions?: string[],
    expiresInDays?: number
): Promise<{ id: string; rawKey: string }> {
    const { rawKey, hashedKey, prefix } = generateApiKey();
    const expiresAt = expiresInDays
        ? new Date(Date.now() + expiresInDays * 24 * 60 * 60 * 1000).toISOString().slice(0, 19).replace("T", " ")
        : null;

    const result = await db.insert(apiKeys).values({
        name,
        key: hashedKey,
        keyPrefix: prefix,
        userId,
        permissions: permissions ? JSON.stringify(permissions) : null,
        expiresAt,
    });

    const id = crypto.randomUUID(); // The id is generated by $defaultFn in schema
    const inserted = await db.query.apiKeys.findFirst({
        where: eq(apiKeys.key, hashedKey),
        columns: { id: true },
    });

    return { id: inserted!.id, rawKey };
}

export async function revokeApiKey(keyId: string): Promise<void> {
    await db.update(apiKeys).set({ isActive: false }).where(eq(apiKeys.id, keyId));
}

export function apiKeyHasPermission(
    apiKeyPermissions: string[],
    userRole: string,
    userPermissions: string | null,
    requiredPermission: Permission
): boolean {
    if (apiKeyPermissions.length > 0 && !apiKeyPermissions.includes(requiredPermission)) return false;
    return hasPermission(userRole, requiredPermission, userPermissions);
}
